### ISSUE TITLE
Running GNOSIS with runGitHub

### ISSUE THREAD

**Issue by tiagochst** [Lydia-King/GNOSIS#1]
Hello,

when I try to run GNOSIS with `runGitHub` it does not respond.

<img width="1162" alt="Screen Shot 2022-04-27 at 1 15 14 PM" src="https://user-images.githubusercontent.com/145529/165582558-d6937b16-6ce4-41f5-8a94-6a80fdc861bb.png">

<img width="1777" alt="Screen Shot 2022-04-27 at 1 14 11 PM" src="https://user-images.githubusercontent.com/145529/165582615-5154a1cd-38a0-4551-8a3b-8f3049760383.png">

**Comment by tiagochst** [comment]
https://lydiaking.shinyapps.io/GNOSIS/ is not working also
<img width="538" alt="Screen Shot 2022-04-27 at 1 18 45 PM" src="https://user-images.githubusercontent.com/145529/165583231-fc7958ca-c4b3-4d58-9752-2ae8341882dc.png">

**Comment by Lydia-King** [comment]
Hi Tiago, I'm not sure what was happening there. I think it was having a bit of a problem with BiocManager earlier for some reason but all seems to be working fine for me now! Could you try again and let me know if it works for you?

**Comment by tiagochst** [comment]
Worked

**Comment by rmaga** [comment]
Hello Lydia,

I ran into the same issue described by Tiago. Are there any changes with the BiocManager libraries?

Thanks!

**Comment by Lydia-King** [comment]
Hello! Everything seems to be working fine for me now, are you still having issues?

**Comment by rmaga** [comment]
Hello Lydia, thanks for your reply. I am still experiencing some issues: 

```This Font Awesome icon ('gears') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
Error: (converted from warning) Error in <Anonymous>: error in evaluating the argument 'x' in selecting a method for function 'levels': Please input clinical patient and/or sample file.

**Comment by Lydia-King** [comment]
Hello, thanks for your update! As far as I'm aware those error/warning messages should not cause any problems with using GNOSIS and so everything should work fine for you. Over the next day or two I will have a closer look and try to sort/suppress these warnings though to avoid any confusion. If the App is not working as expected please let me know.
