### ISSUE TITLE
GNOSIS layout

### ISSUE THREAD

**Issue by jkhlai** [Lydia-King/GNOSIS#3]
Hi Lydia,

I'm trying to implement your beautifully made GNOSIS shiny app on my server which runs on R4.1.1.  

GNOSIS dashboard loads on my browser, but the layout looks like the attached picture
![image](https://user-images.githubusercontent.com/106516076/202330667-ad7a7603-5be7-4269-ad5f-d468d96258a0.png)

Do you think this is a version issue?

**Comment by Lydia-King** [comment]
Hello, I'm not sure it'd be a version issue! What browser are you using?

**Comment by jkhlai** [comment]
Hello, I seem to have fixed the issue by updating all my R packages and maintaining the same R4.1.1 version.  thanks once again!
